var MoscowMetroMap = {
    // линия 1
    Bulvar_Rokossovskgo: { Cherkizovskaya: 1 },
    Cherkizovskaya: { Bulvar_Rokossovskgo: 1, Preobrazhenskaya_Ploshchad: 1 },
    Preobrazhenskaya_Ploshchad: { Cherkizovskaya: 1, Sokolniki: 1 },
    Sokolniki: { Preobrazhenskaya_Ploshchad: 1, Krasnoselskaya: 1 },
    Krasnoselskaya: { Sokolniki: 1, Komsomolskaya_1: 1 },
    Komsomolskaya_1: { Krasnoselskaya: 1, Krasniye_Vorota: 1, Komsomolskaya_5: 1 },
    Krasniye_Vorota: { Komsomolskaya_1: 1, Chistye_Prudy: 1 },
    Chistye_Prudy: { Krasniye_Vorota: 1, Lubyanka: 1, Turgenevskaya: 1, Sretensky_Bulvar: 1 },
    Lubyanka: { Chistye_Prudy: 1, Okhotny_Ryad: 1, Kuznetsky_Most: 1 },
    Okhotny_Ryad: { Lubyanka: 1, Biblioteka_Imeni_Lenina: 1, Teatralnaya: 1 },
    Biblioteka_Imeni_Lenina: { Okhotny_Ryad: 1, Kropotkinskaya: 1, Arbatskaya_3: 1, Aleksandrovsky_Sad: 1, Borovitskaya: 1 },
    Kropotkinskaya: { Biblioteka_Imeni_Lenina: 1, Park_Kultury_1: 1 },
    Park_Kultury_1: { Kropotkinskaya: 1, Frunzenskaya: 1, Park_Kultury_5: 1 },
    Frunzenskaya: { Park_Kultury_1: 1, Sportivnaya: 1 },
    Sportivnaya: { Frunzenskaya: 1, Vorobyovy_Gory: 1 },
    Vorobyovy_Gory: { Sportivnaya: 1, Universitet: 1 },
    Universitet: { Vorobyovy_Gory: 1, Prospekt_Vernadskogo: 1 },
    Prospekt_Vernadskogo: { Universitet: 1, Yugo_Zapadnaya: 1 },
    Yugo_Zapadnaya: { Prospekt_Vernadskogo: 1, Troparyovo: 1 },
    Troparyovo: { Yugo_Zapadnaya: 1, Rumyantsevo: 1 },
    Rumyantsevo: { Troparyovo: 1, Salaryevo: 1 },
    Salaryevo: { Rumyantsevo: 1 },

    // линия 2
    Rechnoy_Vokzal: { Vodny_Stadion: 1 },
    Vodny_Stadion: { Rechnoy_Vokzal: 1, Voykovskaya: 1 },
    Voykovskaya: { Vodny_Stadion: 1, Sokol: 1 },
    Sokol: { Voykovskaya: 1, Aeroport: 1 },
    Aeroport: { Sokol: 1, Dinamo: 1 },
    Dinamo: { Aeroport: 1, Belorusskaya_2: 1 },
    Belorusskaya_2: { Dinamo: 1, Mayakovskaya: 1, Belorusskaya_5: 1 },
    Mayakovskaya: { Belorusskaya_2: 1, Tverskaya: 1 },
    Tverskaya: { Mayakovskaya: 1, Teatralnaya: 1, Pushkinskaya: 1, Chekhovskaya: 1 },
    Teatralnaya: { Tverskaya: 1, Novokuznetskaya: 1, Okhotny_Ryad: 1, Ploshchad_Revolyutsii: 1 },
    Novokuznetskaya: { Teatralnaya: 1, Paveletskaya_2: 1, Tretyakovskaya_8: 1 },
    Paveletskaya_2: { Novokuznetskaya: 1, Avtozavodskaya: 1, Paveletskaya_5: 1 },
    Avtozavodskaya: { Paveletskaya_2: 1, Tekhnopark: 1 },
    Tekhnopark: { Avtozavodskaya: 1, Kolomenskaya: 1 },
    Kolomenskaya: { Tekhnopark: 1, Kashirskaya_2: 1 },
    Kashirskaya_2: { Kolomenskaya: 1, Kantemirovskaya: 1, Kashirskaya_11: 1 },
    Kantemirovskaya: { Kashirskaya_2: 1, Tsaritsyno: 1 },
    Tsaritsyno: { Kantemirovskaya: 1, Orekhovo: 1 },
    Orekhovo: { Tsaritsyno: 1, Domodedovskaya: 1 },
    Domodedovskaya: { Orekhovo: 1, Krasnogvardeyskaya: 1 },
    Krasnogvardeyskaya: { Domodedovskaya: 1, Alma_Atinskaya: 1, Zyablikovo: 1 },
    Alma_Atinskaya: { Krasnogvardeyskaya: 1 },

    // линия 3
    Pyatnitskoye_Shosse: { Mitino: 1 },
    Mitino: { Pyatnitskoye_Shosse: 1, Volokolamskaya: 1 },
    Volokolamskaya: { Mitino: 1, Myakinino: 1 },
    Myakinino: { Volokolamskaya: 1, Strogino: 1 },
    Strogino: { Myakinino: 1, Krylatskoye: 1 },
    Krylatskoye: { Strogino: 1, Molodyozhnaya: 1 },
    Molodyozhnaya: { Krylatskoye: 1, Kuntsevskaya_3: 1 },
    Kuntsevskaya_3: { Molodyozhnaya: 1, Slavyansky_Bulvar: 1, Kuntsevskaya_4: 1 },
    Slavyansky_Bulvar: { Kuntsevskaya_3: 1, Park_Pobedy_3: 1 },
    Park_Pobedy_3: { Slavyansky_Bulvar: 1, Kiyevskaya_3: 1, Park_Pobedy_8a: 1 },
    Kiyevskaya_3: { Park_Pobedy_3: 1, Smolenskaya_3: 1, Kiyevskaya_5: 1, Kiyevskaya_4: 1 },
    Smolenskaya_3: { Kiyevskaya_3: 1, Arbatskaya_3: 1 },
    Arbatskaya_3: { Smolenskaya_3: 1, Ploshchad_Revolyutsii: 1, Biblioteka_Imeni_Lenina: 1, Aleksandrovsky_Sad: 1, Borovitskaya: 1 },
    Ploshchad_Revolyutsii: { Arbatskaya_3: 1, Kurskaya_3: 1, Teatralnaya: 1 },
    Kurskaya_3: { Ploshchad_Revolyutsii: 1, Baumanskaya: 1, Kurskaya_5: 1, Chkalovskaya: 1 },
    Baumanskaya: { Kurskaya_3: 1, Elektrozavodskaya: 1 },
    Elektrozavodskaya: { Baumanskaya: 1, Semyonovskaya: 1 },
    Semyonovskaya: { Elektrozavodskaya: 1, Partizanskaya: 1 },
    Partizanskaya: { Semyonovskaya: 1, Izmaylovskaya: 1 },
    Izmaylovskaya: { Partizanskaya: 1, Pervomayskaya: 1 },
    Pervomayskaya: { Izmaylovskaya: 1, Shchyolkovskaya: 1 },
    Shchyolkovskaya: { Pervomayskaya: 1 },

    // линия 4
    Mezhdunarodnaya: { Mezhdunarodnaya: 1 },
    Vystavochnaya: { Mezhdunarodnaya: 1, Kiyevskaya_4: 1, Delovoy_Tsentr_8a: 1 },
    Kuntsevskaya_4: { Kuntsevskaya_3: 1, Volokolamskaya: 1, Kuntsevskaya_3: 1 },
    Pionerskaya: { Kuntsevskaya_4: 1, Filyovsky_Park: 1 },
    Filyovsky_Park: { Pionerskaya: 1, Bagrationovskaya: 1 },
    Bagrationovskaya: { Filyovsky_Park: 1, Fili: 1 },
    Fili: { Bagrationovskaya: 1, Kutuzovskaya: 1 },
    Kutuzovskaya: { Fili: 1, Studencheskaya: 1 },
    Studencheskaya: { Kutuzovskaya: 1, Kiyevskaya_4: 1 },
    Kiyevskaya_4: { Studencheskaya: 1, Smolenskaya_4: 1, Kiyevskaya_5: 1, Kiyevskaya_3: 1 },
    Smolenskaya_2_4: { Kiyevskaya_4: 1, Volokolamskaya: 1 },
    Arbatskaya_2_4: { Smolenskaya_2_4: 1, Aleksandrovsky_Sad: 1 },
    Aleksandrovsky_Sad: { Arbatskaya_4: 1, Biblioteka_Imeni_Lenina: 1, Arbatskaya_3: 1 },

    // линия 5
    Komsomolskaya_5: { Prospekt_Mira_5: 1, Kurskaya_5: 1, Komsomolskaya_1: 1 },
    Kurskaya_5: { Komsomolskaya_5: 1, Taganskaya_5: 1, Kurskaya_3: 1, Chkalovskaya: 1 },
    Taganskaya_5: { Kurskaya_5: 1, Paveletskaya_5: 1, Taganskaya_7: 1, Marksistskaya: 1 },
    Paveletskaya_5: { Taganskaya_5: 1, Dobryninskaya: 1, Paveletskaya_2: 1 },
    Dobryninskaya: { Taganskaya_5: 1, Oktyabrskaya_5: 1, Serpukhovskaya: 1 },
    Oktyabrskaya_5: { Dobryninskaya: 1, Park_Kultury_5: 1, Oktyabrskaya_6: 1 },
    Park_Kultury_5: { Oktyabrskaya_5: 1, Kiyevskaya_5: 1, Park_Kultury_1: 1 },
    Kiyevskaya_5: { Park_Kultury_5: 1, Krasnopresnenskaya: 1, Kiyevskaya_3: 1, Kiyevskaya_4: 1 },
    Krasnopresnenskaya: { Kiyevskaya_5: 1, Belorusskaya_5: 1, Barrikadnaya: 1 },
    Belorusskaya_5: { Krasnopresnenskaya: 1, Novoslobodskaya: 1, Belorusskaya_2: 1 },
    Novoslobodskaya: { Belorusskaya_5: 1, Prospekt_Mira_5: 1, Mendeleyevskaya: 1 },
    Prospekt_Mira_5: { Novoslobodskaya: 1, Komsomolskaya_5: 1, Prospekt_Mira_6: 1 },

    // линия 6
    Medvedkovo: { Babushkinskaya: 1 },
    Babushkinskaya: { Medvedkovo: 1, Sviblovo: 1 },
    Sviblovo: { Babushkinskaya: 1, Botanichesky_Sad: 1 },
    Botanichesky_Sad: { Sviblovo: 1, VDNKh: 1 },
    VDNKh: { Botanichesky_Sad: 1, Alekseyevskaya: 1, Timiryazevskaya: 4 },
    Alekseyevskaya: { VDNKh: 1, Rizhskaya: 1 },
    Rizhskaya: { Alekseyevskaya: 1, Prospekt_Mira_6: 1 },
    Prospekt_Mira_6: { Rizhskaya: 1, Sukharevskaya: 1, Prospekt_Mira_5: 1 },
    Sukharevskaya: { Prospekt_Mira_6: 1, Turgenevskaya: 1 },
    Turgenevskaya: { Sukharevskaya: 1, Kitay_Gorod_6a: 1, Chistye_Prudy: 1, Sretensky_Bulvar: 1 },
    Kitay_Gorod_6a: { Turgenevskaya: 1, Tretyakovskaya_6a: 1, Kitay_Gorod_7a: 1 },
    Tretyakovskaya_6a: { Kitay_Gorod_6a: 1, Oktyabrskaya_6: 1, Tretyakovskaya_8: 1 },
    Oktyabrskaya_6: { Tretyakovskaya_6a: 1, Shabolovskaya: 1, Oktyabrskaya_5: 1 },
    Shabolovskaya: { Oktyabrskaya_6: 1, Leninsky_Prospekt: 1 },
    Leninsky_Prospekt: { Shabolovskaya: 1, Akademicheskaya: 1 },
    Akademicheskaya: { Leninsky_Prospekt: 1, Profsoyuznaya: 1 },
    Profsoyuznaya: { Akademicheskaya: 1, Novye_Cheryomushki: 1 },
    Novye_Cheryomushki: { Profsoyuznaya: 1, Kaluzhskaya: 1 },
    Kaluzhskaya: { Novye_Cheryomushki: 1, Belyayevo: 1 },
    Belyayevo: { Kaluzhskaya: 1, Konkovo: 1 },
    Konkovo: { Belyayevo: 1, Tyoply_Stan: 1 },
    Tyoply_Stan: { Konkovo: 1, Yasenevo: 1 },
    Yasenevo: { Tyoply_Stan: 1, Novoyasenevskaya: 1 },
    Novoyasenevskaya: { Yasenevo: 1, Bittsevsky_Park: 1 },

    // линия 7
    Planernaya: { Skhodnenskaya: 1 },
    Skhodnenskaya: { Planernaya: 1, Tushinskaya: 1 },
    Tushinskaya: { Skhodnenskaya: 1, Spartak: 1 },
    Spartak: { Tushinskaya: 1, Shchukinskaya: 1 },
    Shchukinskaya: { Spartak: 1, Oktyabrskoye_Pole: 1 },
    Oktyabrskoye_Pole: { Shchukinskaya: 1, Polezhaevskaya: 1 },
    Polezhaevskaya: { Oktyabrskoye_Pole: 1, Begovaya: 1 },
    Begovaya: { Polezhaevskaya: 1, Ulitsa_1905_Goda: 1 },
    Ulitsa_1905_Goda: { Begovaya: 1, Barrikadnaya: 1 },
    Barrikadnaya: { Ulitsa_1905_Goda: 1, Pushkinskaya: 1, Krasnopresnenskaya: 1 },
    Pushkinskaya: { Barrikadnaya: 1, Kuznetsky_Most: 1, Tverskaya: 1, Chekhovskaya: 1 },
    Kuznetsky_Most: { Pushkinskaya: 1, Kitay_Gorod_7a: 1, Lubyanka: 1 },
    Kitay_Gorod_7a: { Kuznetsky_Most: 1, Taganskaya_7: 1, Kitay_Gorod_6a: 1 },
    Taganskaya_7: { Kitay_Gorod_7a: 1, Proletarskaya: 1, Taganskaya_5: 1, Marksistskaya: 1 },
    Proletarskaya: { Taganskaya_7: 1, Volgogradsky_Prospekt: 1, Krestyanskaya_Zastava: 1 },
    Volgogradsky_Prospekt: { Proletarskaya: 1, Tekstilshchiki: 1 },
    Tekstilshchiki: { Volgogradsky_Prospekt: 1, Kuzminki: 1 },
    Kuzminki: { Tekstilshchiki: 1, Ryazanskiy_Prospekt: 1 },
    Ryazanskiy_Prospekt: { Kuzminki: 1, Vykhino: 1 },
    Vykhino: { Ryazanskiy_Prospekt: 1, Lermontovsky_Prospekt: 1 },
    Lermontovsky_Prospekt: { Vykhino: 1, Zhulebino: 1 },
    Zhulebino: { Lermontovsky_Prospekt: 1, Kotelniki: 1 },
    Kotelniki: { Zhulebino: 1 },

    //8			
    Tretyakovskaya_8: { Marksistskaya: 1, Novokuznetskaya: 1, Tretyakovskaya_6a: 1 },
    Marksistskaya: { Tretyakovskaya_8: 1, Ploshchad_Ilyicha: 1, Taganskaya_5: 1, Taganskaya_7: 1 },
    Ploshchad_Ilyicha: { Marksistskaya: 1, Aviamotornaya: 1, Rimskaya: 1 },
    Aviamotornaya: { Ploshchad_Ilyicha: 1, Shosse_Entuziastov: 1 },
    Shosse_Entuziastov: { Aviamotornaya: 1, Perovo: 1 },
    Perovo: { Shosse_Entuziastov: 1, Novogireevo: 1 },
    Novogireevo: { Perovo: 1, Novokosino: 1 },
    Novokosino: { Novogireevo: 1 },

    //8a
    Park_Pobedy_8a: { Park_Pobedy_3: 1, Delovoy_Tsentr_8a: 1 },
    Delovoy_Tsentr_8a: { Park_Pobedy_8a: 1, Vystavochnaya: 1 },

    //9
    Altufyevo: { Bibirevo: 1 },
    Bibirevo: { Altufyevo: 1, Otradnoye: 1 },
    Otradnoye: { Bibirevo: 1, Vladykino: 1 },
    Vladykino: { Otradnoye: 1, Petrovsko_Razumovskaya: 1 },
    Petrovsko_Razumovskaya: { Vladykino: 1, Timiryazevskaya: 1 },
    Timiryazevskaya: { Petrovsko_Razumovskaya: 1, Dmitrovskaya: 1, VDNKh: 4 },
    Dmitrovskaya: { Timiryazevskaya: 1, Savyolovskaya: 1 },
    Savyolovskaya: { Dmitrovskaya: 1, Mendeleyevskaya: 1 },
    Mendeleyevskaya: { Savyolovskaya: 1, Tsvetnoy_Bulvar: 1, Novoslobodskaya: 1 },
    Tsvetnoy_Bulvar: { Mendeleyevskaya: 1, Chekhovskaya: 1, Trubnaya: 1 },
    Chekhovskaya: { Tsvetnoy_Bulvar: 1, Borovitskaya: 1, Tverskaya: 1, Pushkinskaya: 1 },
    Borovitskaya: { Chekhovskaya: 1, Polyanka: 1, Biblioteka_Imeni_Lenina: 1, Arbatskaya_3: 1 },
    Polyanka: { Borovitskaya: 1, Serpukhovskaya: 1 },
    Serpukhovskaya: { Polyanka: 1, Tulskaya: 1, Dobryninskaya: 1 },
    Tulskaya: { Serpukhovskaya: 1, Nagatinskaya: 1 },
    Nagatinskaya: { Tulskaya: 1, Nagornaya: 1 },
    Nagornaya: { Nagatinskaya: 1, Nakhimovsky_Prospekt: 1 },
    Nakhimovsky_Prospekt: { Nagornaya: 1, Sevastopolskaya: 1 },
    Sevastopolskaya: { Nakhimovsky_Prospekt: 1, Chertanovskaya: 1, Kakhovskaya_11: 1 },
    Chertanovskaya: { Sevastopolskaya: 1, Yuzhnaya: 1 },
    Yuzhnaya: { Chertanovskaya: 1, Prazhskaya: 1 },
    Prazhskaya: { Yuzhnaya: 1, Ulitsa_Akademika_Yangelya: 1 },
    Ulitsa_Akademika_Yangelya: { Prazhskaya: 1, Annino: 1 },
    Annino: { Ulitsa_Akademika_Yangelya: 1, Bulvar_Dmitriya_Donskogo: 1 },
    Bulvar_Dmitriya_Donskogo: { Annino: 1, Ulitsa_Starokachalovskaya: 1 },

    //10		
    Marina_Roshcha: { Dostoyevskaya: 1 },
    Dostoyevskaya: { Marina_Roshcha: 1, Trubnaya: 1 },
    Trubnaya: { Dostoyevskaya: 1, Sretensky_Bulvar: 1, Tsvetnoy_Bulvar: 1 },
    Sretensky_Bulvar: { Trubnaya: 1, Chkalovskaya: 1, Chistye_Prudy: 1, Turgenevskaya: 1 },
    Chkalovskaya: { Sretensky_Bulvar: 1, Rimskaya: 1, Kurskaya_5: 1, Kurskaya_3: 1 },
    Rimskaya: { Chkalovskaya: 1, Krestyanskaya_Zastava: 1, Ploshchad_Ilyicha: 1 },
    Krestyanskaya_Zastava: { Rimskaya: 1, Dubrovka: 1, Proletarskaya: 1 },
    Dubrovka: { Krestyanskaya_Zastava: 1, Kozhukhovskaya: 1 },
    Kozhukhovskaya: { Dubrovka: 1, Pechatniki: 1 },
    Pechatniki: { Kozhukhovskaya: 1, Volzhskaya: 1 },
    Volzhskaya: { Pechatniki: 1, Lyublino: 1 },
    Lyublino: { Volzhskaya: 1, Bratislavskaya: 1 },
    Bratislavskaya: { Lyublino: 1, Marino: 1 },
    Marino: { Bratislavskaya: 1, Borisovo: 1 },
    Borisovo: { Marino: 1, Shipilovskaya: 1 },
    Shipilovskaya: { Borisovo: 1, Zyablikovo: 1 },
    Zyablikovo: { Shipilovskaya: 1, Krasnogvardeyskaya: 1 },

    //11
    Kakhovskaya_11: { Varshavskaya: 1, Sevastopolskaya: 1 },
    Varshavskaya: { Kakhovskaya_11: 1, Kashirskaya_11: 1 },
    Kashirskaya_11: { Varshavskaya: 1, Kashirskaya_2: 1 },

    //12
    Bittsevsky_Park: { Lesoparkovaya: 1, Novoyasenevskaya: 1 },
    Lesoparkovaya: { Bittsevsky_Park: 1, Ulitsa_Starokachalovskaya: 1 },
    Ulitsa_Starokachalovskaya: { Lesoparkovaya: 1, Ulitsa_Skobelevskaya: 1, Bulvar_Dmitriya_Donskogo: 1 },
    Ulitsa_Skobelevskaya: { Ulitsa_Starokachalovskaya: 1, Bulvar_Admirala_Ushakova: 1 },
    Bulvar_Admirala_Ushakova: { Ulitsa_Skobelevskaya: 1, Ulitsa_Gorchakova: 1 },
    Ulitsa_Gorchakova: { Bulvar_Admirala_Ushakova: 1, Buninskaya_Alleya: 1 },
    Buninskaya_Alleya: { Ulitsa_Gorchakova: 1 },

};


MoscowMetroPathFinder = new Graph(MoscowMetroMap);



//console.log(MoscowMetroPathFinder.findShortestPath('Bulvar_Rokossovskgo', 'Kantemirovskaya'));