//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoscowMetro1._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public short id { get; set; }
        public string Name { get; set; }
        public string Relations { get; set; }
        public byte Line { get; set; }
    }
}
